# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_stacked_widget.ui'
#
# Created: Wed Mar 27 23:06:20 2019
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from final_website_scraper import *
from final_chart_creator import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(756, 722)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtGui.QFrame.Plain)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_3 = QtGui.QGridLayout(self.page)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.widget_3 = QtGui.QWidget(self.page)
        self.widget_3.setStyleSheet(_fromUtf8("background:white;"))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem = QtGui.QSpacerItem(168, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_9 = QtGui.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_7.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_7.addWidget(self.label_10)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        spacerItem1 = QtGui.QSpacerItem(158, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.gridLayout.addWidget(self.widget_3, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.label_11 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_8.addWidget(self.label_11)
        self.lineEdit_2 = QtGui.QLineEdit(self.page)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_8.addWidget(self.lineEdit_2)
        self.pushButton_2 = QtGui.QPushButton(self.page)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_8.addWidget(self.pushButton_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.widget_4 = QtGui.QWidget(self.page)
        self.widget_4.setStyleSheet(_fromUtf8("background:white;"))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem4 = QtGui.QSpacerItem(198, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.label_12 = QtGui.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_9.addWidget(self.label_12)
        spacerItem5 = QtGui.QSpacerItem(218, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.gridLayout.addWidget(self.widget_4, 2, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_13 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_10.addWidget(self.label_13)
        spacerItem6 = QtGui.QSpacerItem(338, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout_10, 3, 0, 1, 1)
        self.tableWidget_3 = QtGui.QTableWidget(self.page)
        self.tableWidget_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.tableWidget_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.tableWidget_3.setAlternatingRowColors(True)
        self.tableWidget_3.setRowCount(4)
        self.tableWidget_3.setColumnCount(7)
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 6, item)
        self.tableWidget_3.horizontalHeader().setVisible(False)
        self.tableWidget_3.horizontalHeader().setHighlightSections(True)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget_3, 4, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_15 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout.addWidget(self.label_15)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.tableWidget_4 = QtGui.QTableWidget(self.page)
        self.tableWidget_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.tableWidget_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.tableWidget_4.setAlternatingRowColors(True)
        self.tableWidget_4.setRowCount(4)
        self.tableWidget_4.setColumnCount(7)
        self.tableWidget_4.setObjectName(_fromUtf8("tableWidget_4"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_4.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(1, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(1, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(2, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(2, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(2, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(3, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(3, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(3, 6, item)
        self.tableWidget_4.horizontalHeader().setVisible(False)
        self.tableWidget_4.horizontalHeader().setHighlightSections(True)
        self.tableWidget_4.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget_4, 6, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.widget = QtGui.QWidget(self.page_2)
        self.widget.setStyleSheet(_fromUtf8("background:white;"))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem8 = QtGui.QSpacerItem(128, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem8)
        self.label_26 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_13.addWidget(self.label_26)
        self.label_27 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_13.addWidget(self.label_27)
        spacerItem9 = QtGui.QSpacerItem(188, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem9)
        self.gridLayout_4.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtGui.QWidget(self.page_2)
        self.widget_2.setStyleSheet(_fromUtf8("background:white;"))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_14.setMargin(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        spacerItem10 = QtGui.QSpacerItem(128, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem10)
        self.label_28 = QtGui.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_14.addWidget(self.label_28)
        self.label_29 = QtGui.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_14.addWidget(self.label_29)
        spacerItem11 = QtGui.QSpacerItem(188, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem11)
        self.gridLayout_4.addWidget(self.widget_2, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet(_fromUtf8("background:white;"))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("../PythonFiles/new_chart.png")))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 2, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.widget_7 = QtGui.QWidget(self.page_2)
        self.widget_7.setStyleSheet(_fromUtf8("background: white;"))
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.widget_7)
        self.horizontalLayout_16.setMargin(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem12)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem13)
        self.horizontalLayout_15.addWidget(self.widget_7)
        self.pushButton_8 = QtGui.QPushButton(self.page_2)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout_15.addWidget(self.pushButton_8)
        self.pushButton_9 = QtGui.QPushButton(self.page_2)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout_15.addWidget(self.pushButton_9)
        self.pushButton_10 = QtGui.QPushButton(self.page_2)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout_15.addWidget(self.pushButton_10)
        self.pushButton_11 = QtGui.QPushButton(self.page_2)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.horizontalLayout_15.addWidget(self.pushButton_11)
        self.pushButton_12 = QtGui.QPushButton(self.page_2)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.horizontalLayout_15.addWidget(self.pushButton_12)
        self.pushButton_13 = QtGui.QPushButton(self.page_2)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.horizontalLayout_15.addWidget(self.pushButton_13)
        self.widget_8 = QtGui.QWidget(self.page_2)
        self.widget_8.setStyleSheet(_fromUtf8("background:white;\n"""))
        self.widget_8.setObjectName(_fromUtf8("widget_8"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.widget_8)
        self.horizontalLayout_17.setMargin(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem14)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem15)
        self.horizontalLayout_15.addWidget(self.widget_8)
        self.gridLayout_4.addLayout(self.horizontalLayout_15, 3, 0, 1, 1)
        self.widget_9 = QtGui.QWidget(self.page_2)
        self.widget_9.setStyleSheet(_fromUtf8("background:white;\n"""))
        self.widget_9.setObjectName(_fromUtf8("widget_9"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.widget_9)
        self.horizontalLayout_18.setMargin(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_14.addItem(spacerItem16)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_14.addItem(spacerItem17)
        self.horizontalLayout_18.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_15.addItem(spacerItem18)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_15.addItem(spacerItem19)
        self.horizontalLayout_18.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.label_30 = QtGui.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_16.addWidget(self.label_30)
        self.label_31 = QtGui.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.verticalLayout_16.addWidget(self.label_31)
        self.horizontalLayout_18.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label_32 = QtGui.QLabel(self.widget_9)
        self.label_32.setText(_fromUtf8(""))
        self.label_32.setPixmap(QtGui.QPixmap(_fromUtf8("../Images/Positive.png")))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.verticalLayout_17.addWidget(self.label_32)
        self.label_33 = QtGui.QLabel(self.widget_9)
        self.label_33.setText(_fromUtf8(""))
        self.label_33.setPixmap(QtGui.QPixmap(_fromUtf8("../Images/Negative.png")))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.verticalLayout_17.addWidget(self.label_33)
        self.horizontalLayout_18.addLayout(self.verticalLayout_17)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_18.addItem(spacerItem20)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_18.addItem(spacerItem21)
        self.horizontalLayout_18.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.label_34 = QtGui.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.verticalLayout_19.addWidget(self.label_34)
        self.label_35 = QtGui.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.verticalLayout_19.addWidget(self.label_35)
        self.horizontalLayout_18.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.label_36 = QtGui.QLabel(self.widget_9)
        self.label_36.setText(_fromUtf8(""))
        self.label_36.setPixmap(QtGui.QPixmap(_fromUtf8("../Images/Negative.png")))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.verticalLayout_20.addWidget(self.label_36)
        self.label_37 = QtGui.QLabel(self.widget_9)
        self.label_37.setText(_fromUtf8(""))
        self.label_37.setPixmap(QtGui.QPixmap(_fromUtf8("../Images/Positive.png")))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.verticalLayout_20.addWidget(self.label_37)
        self.horizontalLayout_18.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_21.addItem(spacerItem22)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_21.addItem(spacerItem23)
        self.horizontalLayout_18.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.label_38 = QtGui.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.verticalLayout_22.addWidget(self.label_38)
        self.label_39 = QtGui.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.verticalLayout_22.addWidget(self.label_39)
        self.horizontalLayout_18.addLayout(self.verticalLayout_22)
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.label_40 = QtGui.QLabel(self.widget_9)
        self.label_40.setText(_fromUtf8(""))
        self.label_40.setPixmap(QtGui.QPixmap(_fromUtf8("../Images/Positive.png")))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.verticalLayout_23.addWidget(self.label_40)
        self.label_41 = QtGui.QLabel(self.widget_9)
        self.label_41.setText(_fromUtf8(""))
        self.label_41.setPixmap(QtGui.QPixmap(_fromUtf8("../Images/Positive.png")))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.verticalLayout_23.addWidget(self.label_41)
        self.horizontalLayout_18.addLayout(self.verticalLayout_23)
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        spacerItem24 = QtGui.QSpacerItem(17, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_24.addItem(spacerItem24)
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_24.addItem(spacerItem25)
        self.horizontalLayout_18.addLayout(self.verticalLayout_24)
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_25.addItem(spacerItem26)
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_25.addItem(spacerItem27)
        self.horizontalLayout_18.addLayout(self.verticalLayout_25)
        self.gridLayout_4.addWidget(self.widget_9, 4, 0, 1, 1)
        self.widget_10 = QtGui.QWidget(self.page_2)
        self.widget_10.setStyleSheet(_fromUtf8("background: white;"))
        self.widget_10.setObjectName(_fromUtf8("widget_10"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.widget_10)
        self.horizontalLayout_19.setMargin(0)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        spacerItem28 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem28)
        self.label_42 = QtGui.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.horizontalLayout_19.addWidget(self.label_42)
        self.label_43 = QtGui.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.horizontalLayout_19.addWidget(self.label_43)
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem29)
        self.gridLayout_4.addWidget(self.widget_10, 5, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 756, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionMain_Menu = QtGui.QAction(MainWindow)
        self.actionMain_Menu.setObjectName(_fromUtf8("actionMain_Menu"))
        self.actionInstructions = QtGui.QAction(MainWindow)
        self.actionInstructions.setObjectName(_fromUtf8("actionInstructions"))
        self.menuFile.addAction(self.actionMain_Menu)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        
        self.pushButton_2.clicked.connect(self.clickMethod)
        
        self.pushButton_8.clicked.connect(self.clickMethod2)
        self.pushButton_9.clicked.connect(self.clickMethod3)
        self.pushButton_10.clicked.connect(self.clickMethod4)        
        self.pushButton_11.clicked.connect(self.clickMethod5)
        self.pushButton_12.clicked.connect(self.clickMethod6)
        self.pushButton_13.clicked.connect(self.clickMethod7)        

    def retranslateUi(self, MainWindow):
        #start
        data = data_list()
        #end
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_9.setText(_translate("MainWindow", "Stock Market", None))
        self.label_10.setText(_translate("MainWindow", "Technical Analysis Calculator", None))
        self.label_11.setText(_translate("MainWindow", "Stock Ticker Symbol:", None))
        self.pushButton_2.setText(_translate("MainWindow", "Submit", None))
        self.label_12.setText(_translate("MainWindow", "US Stock Exchanges", None))
        self.label_13.setText(_translate("MainWindow", "New York Stock Exchange:", None))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        item = self.tableWidget_3.item(0, 0)
        item.setText(_translate("MainWindow", "Company:", None))
        item = self.tableWidget_3.item(0, 1)
        item.setText(_translate("MainWindow", "Ticker Symbol", None))
        item = self.tableWidget_3.item(0, 2)
        item.setText(_translate("MainWindow", "Market Cap", None))
        item = self.tableWidget_3.item(0, 3)
        item.setText(_translate("MainWindow", "P/E Ratio", None))
        item = self.tableWidget_3.item(0, 4)
        item.setText(_translate("MainWindow", "Div Yield", None))
        item = self.tableWidget_3.item(0, 5)
        item.setText(_translate("MainWindow", "52-Week High", None))
        item = self.tableWidget_3.item(0, 6)
        item.setText(_translate("MainWindow", "52-Week Low", None))
        item = self.tableWidget_3.item(1, 0)
        item.setText(_translate("MainWindow", "Boeing", None))
        item = self.tableWidget_3.item(1, 1)
        item.setText(_translate("MainWindow", "BA", None))
        item = self.tableWidget_3.item(2, 0)
        item.setText(_translate("MainWindow", "JP Morgan Chase", None))
        item = self.tableWidget_3.item(2, 1)
        item.setText(_translate("MainWindow", "JPM", None))
        item = self.tableWidget_3.item(3, 0)
        item.setText(_translate("MainWindow", "Verizon", None))
        item = self.tableWidget_3.item(3, 1)
        item.setText(_translate("MainWindow", "VZ", None))
        
                #start
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[0][0])
        self.tableWidget_3.setItem(1, 2, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[0][1])
        self.tableWidget_3.setItem(1, 3, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[0][2])
        self.tableWidget_3.setItem(1, 4, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[0][3])
        self.tableWidget_3.setItem(1, 5, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[0][4])
        self.tableWidget_3.setItem(1, 6, item)
        
        
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[1][0])
        self.tableWidget_3.setItem(2, 2, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[1][1])
        self.tableWidget_3.setItem(2, 3, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[1][2])
        self.tableWidget_3.setItem(2, 4, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[1][3])
        self.tableWidget_3.setItem(2, 5, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[1][4])
        self.tableWidget_3.setItem(2, 6, item)
        
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[2][0])
        self.tableWidget_3.setItem(3, 2, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[2][1])
        self.tableWidget_3.setItem(3, 3, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[2][2])
        self.tableWidget_3.setItem(3, 4, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[2][3])
        self.tableWidget_3.setItem(3, 5, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[2][4])
        self.tableWidget_3.setItem(3, 6, item)
        #end
        
        
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.label_15.setText(_translate("MainWindow", "Nasdaq Stock Exchange:", None))
        __sortingEnabled = self.tableWidget_4.isSortingEnabled()
        self.tableWidget_4.setSortingEnabled(False)
        item = self.tableWidget_4.item(0, 0)
        item.setText(_translate("MainWindow", "Company:", None))
        item = self.tableWidget_4.item(0, 1)
        item.setText(_translate("MainWindow", "Ticker Symbol", None))
        item = self.tableWidget_4.item(0, 2)
        item.setText(_translate("MainWindow", "Market Cap", None))
        item = self.tableWidget_4.item(0, 3)
        item.setText(_translate("MainWindow", "P/E Ratio", None))
        item = self.tableWidget_4.item(0, 4)
        item.setText(_translate("MainWindow", "Div Yield", None))
        item = self.tableWidget_4.item(0, 5)
        item.setText(_translate("MainWindow", "52-Week High", None))
        item = self.tableWidget_4.item(0, 6)
        item.setText(_translate("MainWindow", "52-Week Low", None))
        item = self.tableWidget_4.item(1, 0)
        item.setText(_translate("MainWindow", "Apple", None))
        item = self.tableWidget_4.item(1, 1)
        item.setText(_translate("MainWindow", "AAPL", None))
        item = self.tableWidget_4.item(2, 0)
        item.setText(_translate("MainWindow", "Facebook", None))
        item = self.tableWidget_4.item(2, 1)
        item.setText(_translate("MainWindow", "FB", None))
        item = self.tableWidget_4.item(3, 0)
        item.setText(_translate("MainWindow", "Microsoft", None))
        item = self.tableWidget_4.item(3, 1)
        item.setText(_translate("MainWindow", "MSFT", None))
        
        
                #start
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[3][0])
        self.tableWidget_4.setItem(1, 2, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[3][1])
        self.tableWidget_4.setItem(1, 3, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[3][2])
        self.tableWidget_4.setItem(1, 4, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[3][3])
        self.tableWidget_4.setItem(1, 5, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[3][4])
        self.tableWidget_4.setItem(1, 6, item)
        
        
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[4][0])
        self.tableWidget_4.setItem(2, 2, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[4][1])
        self.tableWidget_4.setItem(2, 3, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[4][2])
        self.tableWidget_4.setItem(2, 4, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[4][3])
        self.tableWidget_4.setItem(2, 5, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[4][4])
        self.tableWidget_4.setItem(2, 6, item)
        
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[5][0])
        self.tableWidget_4.setItem(3, 2, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[5][1])
        self.tableWidget_4.setItem(3, 3, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[5][2])
        self.tableWidget_4.setItem(3, 4, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[5][3])
        self.tableWidget_4.setItem(3, 5, item)
        
        item = QtGui.QTableWidgetItem()
        item.setText(data[5][4])
        self.tableWidget_4.setItem(3, 6, item)
        #end


        self.tableWidget_4.setSortingEnabled(__sortingEnabled)
        self.label_26.setText(_translate("MainWindow", "Company:", None))
        self.label_27.setText(_translate("MainWindow", "Apple, Inc.", None))
        self.label_28.setText(_translate("MainWindow", "Current Share Price:", None))
        self.label_29.setText(_translate("MainWindow", "$188.25", None))
        self.pushButton_8.setText(_translate("MainWindow", "3 Month", None))
        self.pushButton_9.setText(_translate("MainWindow", "6 Month", None))
        self.pushButton_10.setText(_translate("MainWindow", "9 Month", None))
        self.pushButton_11.setText(_translate("MainWindow", "1 Year", None))
        self.pushButton_12.setText(_translate("MainWindow", "3 Year", None))
        self.pushButton_13.setText(_translate("MainWindow", "5 Year", None))
        self.label_30.setText(_translate("MainWindow", "50 DMA:", None))
        self.label_31.setText(_translate("MainWindow", "RSI:", None))
        self.label_34.setText(_translate("MainWindow", "100 DMA:", None))
        self.label_35.setText(_translate("MainWindow", "MACD:", None))
        self.label_38.setText(_translate("MainWindow", "200 DMA:", None))
        self.label_39.setText(_translate("MainWindow", "VWAP:", None))
        self.label_42.setText(_translate("MainWindow", "Calculator Rating:", None))
        self.label_43.setText(_translate("MainWindow", "Strong Sell", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionMain_Menu.setText(_translate("MainWindow", "Main Menu", None))
        self.actionInstructions.setText(_translate("MainWindow", "Instructions", None))
        
        #start
        self.tableWidget_3.horizontalHeader().setResizeMode(QtGui.QHeaderView.Stretch)
        self.tableWidget_4.horizontalHeader().setResizeMode(QtGui.QHeaderView.Stretch)
        #end
        
        
        
    def clickMethod(self):
        save_charts(self.lineEdit_2.text())
        self.stackedWidget.setCurrentIndex(1)
        self.label_27.setText(get_company_name(self.lineEdit_2.text()))
        self.label_29.setText(get_share_price(self.lineEdit_2.text()))
        
        pixmap = QtGui.QPixmap('one_year.png')
        self.label.setPixmap(pixmap)
        
    def clickMethod2(self):
        pixmap = QtGui.QPixmap('three_month.png')
        self.label.setPixmap(pixmap)
    
    def clickMethod3(self):
        pixmap = QtGui.QPixmap('six_month.png')
        self.label.setPixmap(pixmap)

    def clickMethod4(self):
        pixmap = QtGui.QPixmap('nine_month.png')
        self.label.setPixmap(pixmap)

    def clickMethod5(self):
        pixmap = QtGui.QPixmap('one_year.png')
        self.label.setPixmap(pixmap)

    def clickMethod6(self):
        pixmap = QtGui.QPixmap('three_year.png')
        self.label.setPixmap(pixmap)

    def clickMethod7(self):
        pixmap = QtGui.QPixmap('five_year.png')
        self.label.setPixmap(pixmap)


if __name__ == "__main__":
    import sys
    
    
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    
    MainWindow.setWindowTitle("Stock Market Technical Analysis")
    MainWindow.setWindowIcon(QtGui.QIcon("..\Images\LogoFinal.png"))
    
    MainWindow.show()
    sys.exit(app.exec_())

